apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort  # Allows external access
  ports:
    - port: 3000          # The port exposed by the service
      targetPort: 3000    # The port on the pod container
      nodePort: 32000     # Optional: Explicitly define the NodePort
  selector:
    app: frontend

