apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP  # Internal access only
  ports:
    - port: 4000         # The service port
      targetPort: 4000   # The port inside the container
  selector:
    app: backend        # Matches the backend pods

